apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ecom
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: ecommerce
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/ecommerce"
