apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/sammielas/ecom/user-service:245ced567e8b7cc343e101883ec67f99f757e3b9
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
            - name: OTEL_SERVICE_NAME
              value: "user-service"
            - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
              value: "true"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=user-service"


            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"  # routed via the OTel Collector, which Prometheus then scrapes at :8889
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"  # routed via the OTel Collector, which forwards to Loki's push API
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecom
spec:
  selector:
    app: user-service
  ports:
    - port: 8000
      targetPort: 8000
