resources:
  - ../../base

images:
  - name: ghcr.io/sammielas/ecom/user-service
    newTag: 1884c5bbbd5f01ff9d3a1e031b1edcb74b10668d
  - name: ghcr.io/sammielas/ecom/product-service
    newTag: 1884c5bbbd5f01ff9d3a1e031b1edcb74b10668d
  - name: ghcr.io/sammielas/ecom/order-service
    newTag: 1884c5bbbd5f01ff9d3a1e031b1edcb74b10668d
  - name: ghcr.io/sammielas/ecom/frontend
    newTag: 1884c5bbbd5f01ff9d3a1e031b1edcb74b10668d
