resources:
  - ../../base

images:
  - name: ghcr.io/sammielas/ecom/user-service
    newTag: ce4fb93620d40380fdc5602a4a3ae8dab3917966
  - name: ghcr.io/sammielas/ecom/product-service
    newTag: ce4fb93620d40380fdc5602a4a3ae8dab3917966
  - name: ghcr.io/sammielas/ecom/order-service
    newTag: ce4fb93620d40380fdc5602a4a3ae8dab3917966
  - name: ghcr.io/sammielas/ecom/frontend
    newTag: ce4fb93620d40380fdc5602a4a3ae8dab3917966
