resources:
  - ../../base

images:
  - name: ghcr.io/sammielas/ecom/user-service
    newTag: a3684a9ce0c6c07015d6d38d572a7e6badcc4eab
  - name: ghcr.io/sammielas/ecom/product-service
    newTag: a3684a9ce0c6c07015d6d38d572a7e6badcc4eab
  - name: ghcr.io/sammielas/ecom/order-service
    newTag: a3684a9ce0c6c07015d6d38d572a7e6badcc4eab
  - name: ghcr.io/sammielas/ecom/frontend
    newTag: a3684a9ce0c6c07015d6d38d572a7e6badcc4eab
