resources:
  - ../../base

images:
  - name: ghcr.io/sammielas/ecom/user-service
    newTag: 7890c7a156ed9db8063a553a1b2b3a8df36df4b6
  - name: ghcr.io/sammielas/ecom/product-service
    newTag: 7890c7a156ed9db8063a553a1b2b3a8df36df4b6
  - name: ghcr.io/sammielas/ecom/order-service
    newTag: 7890c7a156ed9db8063a553a1b2b3a8df36df4b6
  - name: ghcr.io/sammielas/ecom/frontend
    newTag: 7890c7a156ed9db8063a553a1b2b3a8df36df4b6
